In [1]:
from bs4 import BeautifulSoup as bs
import random
import time
import re
import pandas as pd
import numpy as np
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
import undetected_chromedriver as uc
from selenium.webdriver.support import expected_conditions as EC

In [17]:
browser = uc.Chrome(driver_executable_path='../chromedriver-linux64/chromedriver')

In [3]:
URL = 'https://www.inmobiliariaeskala.com/propiedades/casa/tunja/'

In [4]:
browser.get(URL)

In [5]:
html = browser.page_source ## sacamos el html de la pagina

In [6]:
soup = bs(html,"html")

In [11]:
temp=soup.find('div',{'class':'mh-layout__content-right'}).find_all('a')

In [13]:
len(temp)

18

In [19]:
lista = [i.get('href') for i in temp]

In [23]:
df = pd.DataFrame(lista,columns=['urls'])

In [26]:
df.drop_duplicates('urls',inplace=True,ignore_index=True)

In [29]:
URl = 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/?venta-o-orriendo=venta&current_page=2'

In [30]:
browser.get(URl)

In [31]:
html = browser.page_source ## sacamos el html de la pagina

In [32]:
soup = bs(html,"html")

In [33]:
temp=soup.find('div',{'class':'mh-layout__content-right'}).find_all('a')

In [34]:
len(temp)

27

In [35]:
lista = [i.get('href') for i in temp]

In [36]:
lista

['https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/arrienda-vende-apartamento-amoblado-conjunto-san-carlos/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/arrienda-vende-apartamento-amoblado-conjunto-san-carlos/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/arrienda-vende-apartamento-amoblado-conjunto-san-carlos/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-sector-unicentro-2/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-sector-unicentro-2/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-sector-unicentro-2/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-sector-unicentro/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-sector-unicentro/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-sector-unicentro/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-sector-viva-tunja/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-sector-viva-tunja/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-sector-viva-tunja/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/arrienda-apartamento-cerca-de-la-uptc/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/arrienda-apartamento-cerca-de-la-uptc/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/arrienda-apartamento-cerca-de-la-uptc/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-casa-terrazas-de-santa-ines/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-casa-terrazas-de-santa-ines/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-casa-terrazas-de-santa-ines/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-inaltezza/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-inaltezza/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-apartamento-inaltezza/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/arrienda-vende-apartamento-villa-de-aranjuez/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/arrienda-vende-apartamento-villa-de-aranjuez/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/arrienda-vende-apartamento-villa-de-aranjuez/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-arrienda-apartamento-barrio-coeducadores/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-arrienda-apartamento-barrio-coeducadores/',
 'https://www.inmobiliariaeskala.com/propiedades/apartamento/tunja/vende-arrienda-apartamento-barrio-coeducadores/']

In [37]:
df1 = pd.DataFrame(lista,columns=['urls'])
df1.drop_duplicates('urls',inplace=True,ignore_index=True)
df1

                                                urls
0  https://www.inmobiliariaeskala.com/propiedades...
1  https://www.inmobiliariaeskala.com/propiedades...
2  https://www.inmobiliariaeskala.com/propiedades...
3  https://www.inmobiliariaeskala.com/propiedades...
4  https://www.inmobiliariaeskala.com/propiedades...
5  https://www.inmobiliariaeskala.com/propiedades...
6  https://www.inmobiliariaeskala.com/propiedades...
7  https://www.inmobiliariaeskala.com/propiedades...
8  https://www.inmobiliariaeskala.com/propiedades...

In [38]:
df = pd.concat([df,df1],ignore_index=True)
df.to_csv('ursl_eskala.csv',index=False)

## extraccion de datos

In [2]:
df_url = pd.read_csv('ursl_eskala.csv')

In [3]:
browser = uc.Chrome(driver_executable_path='../chromedriver-linux64/chromedriver')

In [26]:
url = str(df_url.iloc[0].values).strip("'[]'")
browser.get(url)

In [5]:
html = browser.page_source ## sacamos el html de la pagina
soup = bs(html,"html")

In [7]:
temp=soup.find('div',{'class':'mh-estate__section mh-estate__section--attributes'})
temp.text

'\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tTipo de propiedad:\n\t\t\t\t\t\t\t\t\t\t\t\t\t\n\n\t\t\t\t\t\t\t\t\tCasa\t\t\t\t\t\t\t\t\t\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tCódigo Inmueble:\n\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t31096\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\n\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tVenta / Arriendo:\n\t\t\t\t\t\t\t\t\t\t\t\t\t\n\n\t\t\t\t\t\t\t\t\tVenta\t\t\t\t\t\t\t\t\t\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tCiudad:\n\t\t\t\t\t\t\t\t\t\t\t\t\t\n\n\t\t\t\t\t\t\t\t\tTunja\t\t\t\t\t\t\t\t\t\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tSector:\n\t\t\t\t\t\t\t\t\t\t\t\t\t\n\n\t\t\t\t\t\t\t\t\tCentro\t\t\t\t\t\t\t\t\t\n\n\n\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tBaños:\n\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t2\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\n\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tTamaño:\n\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t213 m²\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\n\n\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tTamaño Lote:\n\t\t\t\t\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t331 m²\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\n\t\t\t\t\t\n\n\n\t\t\t\t\t\t\t\t\tEstrato:\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t3\t\t\t\t\t\t\t\t\t\t\t\t\t\n\n\n\t\t\t\t\t\t\t\t\tValor :\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t$ 410.000.000\t\t\t\t\t\t\t\t\t\t\t\t\t\n\n\n\t\t\t\t\t\t\t\t\tPrecio Negociable:\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tSi\t\t\t\t\t\t\t\t\t\t\t\t\t\n\n\n'

In [48]:
clave =['Tipo de propiedad',]
valor= []
# Expresión regular para capturar "Casa o Apartamentos"
patron = re.compile(r'Tipo de propiedad:[\s\n\t]*(Casa|Apartamentos)')

# Busca la coincidencia
coincidencia = patron.search(temp.text)

# Extrae el texto "Casa"
if coincidencia:
    resultado = coincidencia.group(0).split(':')[-1].strip()
    print(resultado)
else:
    print("No se encontró coincidencia.")

Casa

In [8]:
l=temp.find_all('li')
len(l)

11

In [20]:
l[0].text.strip('\t\n')

'Tipo de propiedad:\n\t\t\t\t\t\t\t\t\t\t\t\t\t\n\n\t\t\t\t\t\t\t\t\tCasa'

In [43]:
patron= '[\s\n\t]+'
a=re.sub(patron,'',l[5].text)

In [44]:
a.split(':')

['Baños', '2']

In [9]:
valor = []
clave = []
## utilizo re para obterne todos los datos que no tengan saltos de linea tab o espacios
patron = '[\s\n\t]+'

for i in range(len(l)):
    a = re.sub(patron,'',l[i].text)
    a = a.split(':')
    clave.append(a[0])
    valor.append(a[1])

In [10]:
df = pd.DataFrame([valor],columns=clave)
df

,Tipodepropiedad,CódigoInmueble,Venta/Arriendo,Ciudad,Sector,Baños,Tamaño,TamañoLote,Estrato,Valor,PrecioNegociable
0,Casa,31096,Venta,Tunja,Centro,2,213m²,331m²,3,$410.000.000,Si

## automatizo recoleccion

In [18]:
for i in range(1,df_url.shape[0]):
    url = str(df_url.iloc[i].values).strip("'[]'")
    browser.get(url)
    time.sleep(random.randint(11,12))
    html = browser.page_source ## sacamos el html de la pagina
    soup = bs(html,"html")
    temp=soup.find('div',{'class':'mh-estate__section mh-estate__section--attributes'})
    l=temp.find_all('li') # obtengo todo las etiquetas que me interezan
    
    valor = []
    clave = []
    ## utilizo re para obterne todos los datos que no tengan saltos de linea tab o espacios
    patron = '[\s\n\t]+'

    for i in range(len(l)):
        a = re.sub(patron,'',l[i].text)
        a = a.split(':')
        clave.append(a[0])
        valor.append(a[1])
    df1 = pd.DataFrame([valor],columns=clave)
    df = pd.concat([df,df1],ignore_index=True)

In [15]:
df.drop_duplicates(subset='Tipodepropiedad',inplace=True)

In [19]:
df

,Tipodepropiedad,CódigoInmueble,Venta/Arriendo,Ciudad,Sector,Baños,Tamaño,TamañoLote,Estrato,Valor,...,ZonasSociales,Habitaciones,Garaje,Deposito,ValorparaVenta,Garajes,Ascensores,Parqueadero,ValordeAdministración,Administración
0,Casa,31096,Venta,Tunja,Centro,2,213m²,331m²,3,$410.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Casa,30914,Venta,Tunja,Norte,3,139.91m²,87m²,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Casa,30890,Arriendo,Tunja,Norte,3,Aprox.140m²,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Casa,30836,Venta,Tunja,Norte,3,140.10m²,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Casa,30433,Venta,Tunja,Sur,2,135m²,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Casa,29199,Venta,Tunja,Occidente,4,145m²,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Apartamento,31134,"Arriendo,Venta",Tunja,Norte,2,50.31m²,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Apartamento,31006,Venta,Tunja,Unicentro,2,76.84m²,NaN,5,$350.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Apartamento,30948,Venta,Tunja,Unicentro,3,74.33m²,NaN,NaN,$320.000.000,...,Si,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Apartamento,30689,Venta,Tunja,Norte,2,100m²,NaN,5,$390.000.000,...,NaN,NaN,Si,Si,NaN,NaN,NaN,NaN,NaN,NaN
10,Apartamento,30402,"Arriendo,Venta",Tunja,Norte,1,38m²,NaN,3,NaN,...,NaN,2,NaN,NaN,$160.000.000,NaN,NaN,NaN,NaN,NaN
11,Apartamento,30073,Venta,Tunja,Norte,4,232m²,NaN,5,NaN,...,NaN,4,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN
12,Apartamento,30055,Venta,Tunja,Norte,2,78m²,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,Si,Si,NaN,NaN
13,Apartamento,29978,Venta,Tunja,Norte,2,97m²,NaN,5,NaN,...,NaN,NaN,NaN,Si,NaN,NaN,NaN,NaN,$239.200,NaN
14,Apartamento,29237,Venta,Tunja,Norte,2,70m²,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No

In [21]:
precios = []
for i in range(df_url.shape[0]):
    url = str(df_url.iloc[i].values).strip("'[]'")
    browser.get(url)
    time.sleep(random.randint(11,12))
    html = browser.page_source ## sacamos el html de la pagina
    soup = bs(html,"html")
    temp=soup.find('div',{'class':'mh-estate__details__price__single'}).text
    precios.append(temp)

In [23]:
len(precios)

15

In [27]:
precios = [i.strip('\t\n') for i in precios]

In [29]:
df['Valor'] = precios

In [30]:
df

,Tipodepropiedad,CódigoInmueble,Venta/Arriendo,Ciudad,Sector,Baños,Tamaño,TamañoLote,Estrato,Valor,...,ZonasSociales,Habitaciones,Garaje,Deposito,ValorparaVenta,Garajes,Ascensores,Parqueadero,ValordeAdministración,Administración
0,Casa,31096,Venta,Tunja,Centro,2,213m²,331m²,3,$400.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Casa,30914,Venta,Tunja,Norte,3,139.91m²,87m²,4,$580.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Casa,30890,Arriendo,Tunja,Norte,3,Aprox.140m²,NaN,5,$2.200.000 /mes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Casa,30836,Venta,Tunja,Norte,3,140.10m²,NaN,5,$650.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Casa,30433,Venta,Tunja,Sur,2,135m²,NaN,3,$230.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Casa,29199,Venta,Tunja,Occidente,4,145m²,NaN,NaN,Contacte por Precio ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Apartamento,31134,"Arriendo,Venta",Tunja,Norte,2,50.31m²,NaN,NaN,$1.700.000 /mes,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Apartamento,31006,Venta,Tunja,Unicentro,2,76.84m²,NaN,5,$350.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Apartamento,30948,Venta,Tunja,Unicentro,3,74.33m²,NaN,NaN,$320.000.000,...,Si,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Apartamento,30689,Venta,Tunja,Norte,2,100m²,NaN,5,$390.000.000,...,NaN,NaN,Si,Si,NaN,NaN,NaN,NaN,NaN,NaN
10,Apartamento,30402,"Arriendo,Venta",Tunja,Norte,1,38m²,NaN,3,$160.000.000 /mes,...,NaN,2,NaN,NaN,$160.000.000,NaN,NaN,NaN,NaN,NaN
11,Apartamento,30073,Venta,Tunja,Norte,4,232m²,NaN,5,$600.000.000,...,NaN,4,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN
12,Apartamento,30055,Venta,Tunja,Norte,2,78m²,NaN,5,$230.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,Si,Si,NaN,NaN
13,Apartamento,29978,Venta,Tunja,Norte,2,97m²,NaN,5,$340.000.000,...,NaN,NaN,NaN,Si,NaN,NaN,NaN,NaN,$239.200,NaN
14,Apartamento,29237,Venta,Tunja,Norte,2,70m²,NaN,4,$190.000.000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,No

In [31]:
df.to_csv('data_escala.csv',index=False)